### PR TITLE
simplify centos-7, ubuntu-16.04 things

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by mattock** [comment]
@chipitsine I'm generally ok with this. Did you test that this works on all the affected VMs (ubuntu-1604, ubuntu-1804, centos-7)?

**Comment by chipitsine** [comment]
I test a bit different setup.

I run vagrant on Hyper-V

yes, it works

**Comment by chipitsine** [comment]
maybe, I'll try to unify Vagrantfile to support both virtualbox and hyperv

**Comment by mattock** [comment]
As long as Virtualbox users are not affected adding Hyper-V support is ok. In fact, it would pave the way for more providers later. I know that some people refuse to use _Oracle_ Virtualbox and would like to use KVM instead.

**Comment by chipitsine** [comment]
another option for multi-box testing (including server + client) might be Github Action

I'm not sure whether travis-ci supports multi-box run

**Comment by mattock** [comment]
I think Vagrant is best when you need to test random thing <a> on platform <n> and you're not sure if it will work. Especially if you need to have that platfrom <n> available so that you can figure out what you need to do in code to make it work on it. This was the premise on which I set up openvpn-vagrant originally - very few people were able to test their code on other, let alone esoteric platforms. 

So the use-case for Vagrant just different than that of Buildbot or Travis. The former is more of a development tool whereas the latter tools primarily spot regressions.

If you still want to add Hyper-V support to the Vagrantfile I'm all for it :smile:.

**Comment by chipitsine** [comment]
not within this pull request.

I'm going to spent some time on mid term to vagrant+hyperv

**Comment by mattock** [comment]
Ok. I will merge this as-is then.

**Pull request merged**
