### PR TITLE
Dockerized buildbot

### PR DESCRIPTION
**Pull request by mattock**
This PR introduces the dockerized replacement for the largely outdated buildbot environment for OpenVPN 2.x. It is isolated from the rest of openvpn-vagrant except for small amount of refactoring done to Powershell provisioning that "msibuilder" uses.

### CODE REVIEW

**Comment by mattock** [comment]
Added @lstipakov who might be interested in verifying the Windows part.

**Comment by lstipakov** [comment]
I tried with Hyper-V.

- I had to change "ubuntu/focal64" to "generic/ubuntu2004" since former one doesn't have Hyper-V support
- I had to remove "type virtualbox" from vagrant configuration
- When vagrant finally started VM, it asked for some credentials:

```
    buildbot-host: Username (user[@domain]): vagrant
    buildbot-host: Password (will be hidden):
==> buildbot-host: Credentials incorrect. Please try again.
```

vagrant/vagrant didn't help so I gave up.

**Comment by mattock** [comment]
@lstipakov that smells like a problem with the base box (generic/ubuntu2004). Vagrant should handle all that SSH stuff internally and never prompt for a password. I can test if I can reproduce the problem but not right now, need to do things with my buildbot setup and reprovisioning takes probably an hour.

**Comment by mattock** [comment]
I was able to spin up buildbot-host on my Windows 10 laptop. The issues with rebuild-all.sh that @lstipakov had (dos2unix was required to make them work) were notably absent.

I will try out the generic/ubuntu2004 image once I've verified that the current settings are 100% functional on Windows.

**Comment by mattock** [comment]
The whole build chain is working now. We get signed binaries in a signed MSI installers. The only step remaining is to ensure that dependency updates (e.g. openssl) work ok.

**Comment by lstipakov** [comment]
README still says that

> Building MSI packages is a two-phase process which requires using
> openvpn-build-bionic (Ubuntu 18.04) and msibuilder (Windows Server 2016) VMs.
> The former is used to produce Windows binaries and the latter to produce MSI
> packages.

Isn't it now outdated, since everything is built on Windows ?

**Comment by mattock** [comment]
Yes, it is outdated. I won't have time to fix that today. I think I'll make "msibuilder" capable of building and packaging OpenVPN. Basically the same as "buildbot-worker-windows-server-2019" without Buildbot. Then I can modify the documentation to list the manual build steps.

**Comment by mattock** [comment]
@lstipakov updated the Windows build documentation. It only makes sense when https://github.com/OpenVPN/openvpn-build/pull/226 is also merged.

**Comment by mattock** [comment]
@lstipakov reordered the build steps to match https://github.com/OpenVPN/openvpn-build/pull/226. Seems work nicely, all green with latest "master". Explicit rst2html.py calls also removed now that they're not needed.

**Review by lstipakov — APPROVED** [review]

**Comment by mattock** [comment]
I forgot to add that this code (provisioning and buildbot) has been tested in Vagrant and in Amazon EC2. It works nicely in both.

**Pull request merged**
