### PR TITLE
Add openvpn-build VM for Ubuntu 18.04 (openvpn-build-bionic)

### PR DESCRIPTION
**Pull request by mattock**
Signed-off-by: Samuli Seppänen <samuli@openvpn.net>

### CODE REVIEW

**Comment by mattock** [comment]
The curl tricks are required on Ubuntu 18.04 because osslsigncode does not support OpenSSL 1.1. In fact, osslsigncode is effectivity abandoned, so unless a maintainer comes up we need to find some other signing solution.

**Comment by dsommers** [comment]
I would recommend to add that comment of yours, @mattock, to the commit message itself.  But make it clear that osslsigncode depends on libcurl and openssl-1.0, which changes the libcurl dependency to one built against openssl-1.0 and not the default openssl-1.1.

**Comment by mattock** [comment]
@dsommers yes. Some modifications I made today:
* The script will refuse to run without "-f" on Bionic
* It shows a warning explaining the problem if "-f" is not used on Bionic
* curl is reinstalled after installing osslsigncode (that may still leave some previously installed meta-packages in uninstalled state)
* commit message also explains the problem

**Comment by mattock** [comment]
It's been 6 weeks since the latest changes, so I will merge this with a lazy-ACK. I'm now setting up the MSI packager VM and I will need the openvpn-build VM to properly test the interaction (e.g. Samba shares).

If there are any further concerns about this PR I will fix them separately.

**Comment by cron2** [comment]
Hi,

On Fri, Dec 28, 2018 at 01:23:48AM -0800, Samuli Seppänen wrote:
> It's been 6 weeks since the latest changes, so I will merge this with a lazy-ACK. I'm now setting up the MSI packager VM and I will need the openvpn-build VM to properly test the interaction (e.g. Samba shares).

Good enough.  While I intended to test it, my vagrant rig is on the
laptop which I didn't use in weeks...

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de

**Pull request merged**
